# Generated by Django 2.2 on 2019-04-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190409_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc', models.TextField(max_length=300)),
            ],
        ),
    ]
